# Generated by Django 5.1.3 on 2024-11-19 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_profile_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='phone_number9',
        ),
    ]
